In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv('house.csv', ';')

/srv/conda/envs/notebook/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3444: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
  exec(code_obj, self.user_global_ns, self.user_ns)


In [4]:
df

houseSize  lotSize  bedrooms  granite  bathroom  sellingPrice
0       3529     9191         6        0         0        205000
1       3247    10061         5        1         1        224900
2       4032    10150         5        0         1        197900
3       2397    14156         4        1         0        189900
4       2200     9600         4        0         1        195000
5       3536    19994         6        1         1        325000
6       2983     9365         5        0         1        230000

In [5]:
x = np.array(df[['lotSize', 'houseSize', 'bedrooms', 'granite', 'bathroom']]).reshape((-1, 1))

In [6]:
y = np.array(df[['sellingPrice', 'sellingPrice', 'sellingPrice', 'sellingPrice', 'sellingPrice']]).reshape((-1, 1))

In [9]:
plt.scatter(x, y,  color='blue', linewidth=3)

In [10]:
model = LinearRegression()

In [11]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
reg = model.score(x, y)

In [13]:
reg

0.016369563898140593

In [14]:

np.mean((model.predict(x)-y)**2)

1866623835.61799

In [15]:
model.intercept_

array([220536.44839236])

In [16]:
model.coef_

array([[1.14586258]])

In [17]:
x_prev = x

In [18]:
y_prev = model.predict(x_prev)

In [19]:
y_prev

array([[231068.07140549],
       [224580.19745267],
       [220543.32356787],
       [220536.44839236],
       [220536.44839236],
       [232064.9718539 ],
       [224257.06420387],
       [220542.17770528],
       [220537.59425495],
       [220537.59425495],
       [232166.95362392],
       [225156.56633262],
       [220542.17770528],
       [220536.44839236],
       [220537.59425495],
       [236757.27913698],
       [223283.08100714],
       [220541.0318427 ],
       [220537.59425495],
       [220536.44839236],
       [231536.7292025 ],
       [223057.34607802],
       [220541.0318427 ],
       [220536.44839236],
       [220537.59425495],
       [243446.82490465],
       [224588.21849076],
       [220543.32356787],
       [220537.59425495],
       [220537.59425495],
       [231267.45149517],
       [223954.5564816 ],
       [220542.17770528],
       [220536.44839236],
       [220537.59425495]])

In [20]:
y_prev[0][0]

231068.07140548568